const AllActions = () => {
    return ([
['No request for review or appeal has been lodged', 'i'],
['A request for review or an appeal has been lodged', 'i'],
['Withdrawal of request for review or appeal', 'i'],
['Cancellation effected for some of the goods and services at the request of an Office of origin in accordance with Article 6(4) of the Agreement or Article 6(4) of the Protocol', 'n'],
['Cancellation effected for all the goods and services at the request of an Office of origin in accordance with Article 6(4) of the Agreement or Article 6(4) of the Protocol', 'i'],
['Judicial actions or proceedings under Rule 22(1)(b)', 'n'],
['Continuation of effect', 'r'],
['Cancellation of the Recording of a License', 'n'],
['Partial assignment', 'a'],
['Partial assignment to specific Contracting Parties', 'a'],
['Partial assignment of particular Goods and Services', 'a'],
['Division/Merger of basic registration', 'n'],
['Accepted with reserve', 'a'],
['Designated contracting party(ies) for which the second installment has been paid (Rule 40(3))', 'n'], //тонкий момент для определения объема охраны
['Designated contracting party(ies) for which the second installment has not been paid (Rule 40(3))', 'i'],
['Registration', 'r'],
['Subsequent designation', 'r'],
['Replacement of national registration by an international registration', 'n'],
['Final decision confirming the refusal of protection', 'i'],
['Disclaimer', 'i'],
['Final decision confirming the disclaimer', 'i'],
['Statement indicating that protection of the mark is protected for some of the goods and services requested', 'a'],
['Statement indicating that protection of the mark is refused for all the goods and services requested', 'i'],
['Statement indicating that the mark is protected for all the goods and services requested', 'a'],
['Further statement under Rule 18ter(4) indicating the goods and services for which the mark is protected', 'a'],
['Further statement under Rule 18ter(4) indicating that protection of the mark is refused for all the goods and services requested', 'i'],
['Further statement under Rule 18ter(4) indicating that protection of the mark is granted for all the goods and services requested', 'a'],
['Merger of international registrations', 'n'],
['Statement of grant of protection made under Rule 18ter(1) where no notification of provisional refusal has been communicated', 'a'],
['Grant of protection', 'a'],
['Grant of protection subject to opposition', 'i'],
['Restriction of the holder\'s right of disposal of the international registration', 'n'],
['Partial invalidation', 'a'],
['Total invalidation', 'i'],
['Ex Officio examination completed but opposition or observations by third parties still possible, under Rule 18bis(1)', 'i'],
['Limitation', 'n'],
['Change in the name or address of the licensee', 'n'],
['Declaration that a limitation has no effect', 'n'],
['New licence', 'n'],
['Subsequent designations resulting from Conversion (Rule 24(7))', 'r'],
['Opposition possible after the 18 months time limit', 'i'],
['Cancellation effected with respect to a designated Contracting Party following the non payment of the second part of the individual fee (Rule 34(3))', 'i'],
['Cancellation effected for some of the goods and services at the request of the holder under Rule 25', 'n'],
['Statement of grant of protection following a provisional refusal under Rule 18ter(2)(ii)', 'a'],
['Statement of grant of protection following a provisional refusal (acceptation with reserve) under Rule 18ter(2)(ii)', 'a'],
['Confirmation of total provisional refusal under Rule 18ter(3)', 'i'],
['Statement of grant of protection following a provisional refusal under Rule 18ter(2)(i)', 'a'],
['Cancellation effected for all the goods and services at the request of the holder under Rule 25', 'i'],
['Complementary renewal', 'a'],
['Renewal', 'a'],
['Designated contracting party(ies) which has not been the subject of a renewal (Rule 31(4)(a))', 'i'],
['Designated contracting party(ies) which has not been the subject of a renewal (Rule 31(4)(b))', 'i'],
['Partial refusal of protection', 'i'],
['Total refusal of protection', 'i'],
['Removal of restriction of the holder\'s right of disposal of the international registration', 'n'],
['Renunciation', 'i'],
['Declaration that a change in ownership has no effect', 'n'],
['Balances of fees', 'n'],
['Seniority Claimed Subsequent to the International Registration', 'n'],
['Final refusal of seniority claim', 'n'],
['Other final decision - Awaiting translation before publication', 'a'],
['Partial provisional refusal of protection - Awaiting translation before publication', 'i'],
['Partial provisional refusal of protection', 'i'],
['Statement indicating the goods and services for which protection of the mark is granted under Rule 18ter(2)(ii)', 'a']
    ]);
}

exports.AllActions = AllActions;
